export const awsServices = [
	'Amplify',
	'API Gateway Endpoint',
	'App Mesh Mesh',
	'App Mesh Virtual Gateway',
	'App Mesh Virtual Node',
	'App Mesh Virtual Router',
	'App Mesh Virtual Service',
	'Application Discovery Service Migration Evaluator Collector',
	'Application Discovery Service',
	'Athena Data Source Connectors',
	'Aurora Instance',
	'Aurora MariaDB Instance Alternate',
	'Aurora MariaDB Instance',
	'Aurora MySQL Instance Alternate',
	'Aurora MySQL Instance',
	'Aurora Oracle Instance Alternate',
	'Aurora Oracle Instance',
	'Aurora Piops Instance',
	'Aurora PostgreSQL Instance Alternate',
	'Aurora PostgreSQL Instance',
	'Aurora SQL Server Instance Alternate',
	'Aurora SQL Server Instance',
	'Aurora Trusted Language Extensions For PostgreSQL',
	'Aurora',
	'Backup Audit Manager',
	'Backup Backup Plan',
	'Backup Backup Restore',
	'Backup Backup Vault',
	'Backup Compliance Reporting',
	'Backup Compute',
	'Backup Database',
	'Backup Gateway',
	'Backup Legal Hold',
	'Backup Recovery Point Objective',
	'Backup Recovery Time Objective',
	'Backup Storage',
	'Backup Vault Lock',
	'Backup Virtual Machine Monitor',
	'Backup Virtual Machine',
	'Backup',
	'Braket Chandelier',
	'Braket Chip',
	'Braket Embedded Simulator',
	'Braket Managed Simulator',
	'Braket Noise Simulator',
	'Braket QPU',
	'Braket Simulator 1',
	'Braket Simulator 2',
	'Braket Simulator 3',
	'Braket Simulator 4',
	'Braket Simulator',
	'Braket State Vector',
	'Braket Tensor Network',
	'Certificate Manager Certificate Authority',
	'Cloud Digital Interface',
	'Cloud Map Namespace',
	'Cloud Map Resource',
	'Cloud Map Service',
	'Cloud WAN Core Network Edge',
	'Cloud WAN Segment Network',
	'Cloud WAN Transit Gateway Route Table Attachment',
	'Cloud9 Cloud9',
	'Cloudformation Change Set',
	'Cloudformation Stack',
	'Cloudformation Template',
	'CloudFront Download Distribution',
	'CloudFront Edge Location',
	'CloudFront Functions',
	'CloudFront Streaming Distribution',
	'Cloudsearch Search Documents',
	'Cloudtrail Cloudtrail Lake',
	'CloudWatch Alarm',
	'CloudWatch Cross Account Observability',
	'CloudWatch Data Protection',
	'CloudWatch Event Event Based',
	'CloudWatch Event Time Based',
	'CloudWatch Evidently',
	'CloudWatch Logs',
	'CloudWatch Metrics Insights',
	'CloudWatch Rule',
	'CloudWatch Rum',
	'CloudWatch Synthetics',
	'Data Exchange For APIs',
	'Database Migration Service Database Migration Workflow Or Job',
	'DataSync Agent',
	'DataSync Discovery',
	'DataZone Business Data Catalog',
	'DataZone Data Portal',
	'DataZone Data Projects',
	'Devops Guru Insights',
	'Direct Connect Gateway',
	'Directory Service Ad Connector',
	'Directory Service Simple Ad',
	'Directory Service',
	'DocumentDB Elastic Clusters',
	'DynamoDB Attribute',
	'DynamoDB Attributes',
	'DynamoDB Global Secondary Index',
	'DynamoDB Item',
	'DynamoDB Items',
	'DynamoDB Standard Access Table Class',
	'DynamoDB Standard Infrequent Access Table Class',
	'DynamoDB Stream',
	'DynamoDB Table',
	'DynamoDB',
	'EC2 AMI',
	'EC2 Auto Scaling',
	'EC2 Aws Microservice Extractor For ',
	'EC2 DB Instance',
	'EC2 Elastic IP Address',
	'EC2 Instance With CloudWatch',
	'EC2 Instance',
	'EC2 Instances',
	'EC2 Rescue',
	'EC2 Spot Instance',
	'Elastic Beanstalk Application',
	'Elastic Beanstalk Deployment',
	'Elastic Block Store Multiple Volumes',
	'Elastic Block Store Snapshot',
	'Elastic Block Store Volume Gp3',
	'Elastic Block Store Volume',
	'Elastic Block Store',
	'Elastic Container Registry Image',
	'Elastic Container Registry Registry',
	'Elastic Container Service Container 1',
	'Elastic Container Service Container 2',
	'Elastic Container Service Container 3',
	'Elastic Container Service Copiiot Cli',
	'Elastic Container Service Ecs Service Connect',
	'Elastic Container Service Service',
	'Elastic Container Service Task',
	'Elastic File System EFS Intelligent Tiering',
	'Elastic File System EFS One Zone Infrequent Access',
	'Elastic File System EFS One Zone',
	'Elastic File System EFS Standard Infrequent Access',
	'Elastic File System EFS Standard',
	'Elastic File System Elastic Throughput',
	'Elastic File System File System',
	'Elastic Kubernetes Service Eks On Outposts',
	'Elastic Load Balancing Application Load Balancer',
	'Elastic Load Balancing Classic Load Balancer',
	'Elastic Load Balancing Gateway Load Balancer',
	'Elastic Load Balancing Network Load Balancer',
	'Elasticache Cache Node',
	'Elasticache Elasticache For Memcached',
	'Elasticache Elasticache For Redis',
	'Elemental Mediaconnect Mediaconnect Gateway',
	'EMR Cluster',
	'EMR Engine',
	'EMR HDFS Cluster',
	'EventBridge Custom Event Bus',
	'EventBridge Default Event Bus',
	'EventBridge Event',
	'EventBridge Pipes',
	'EventBridge Rule',
	'EventBridge Saas Partner Event',
	'EventBridge Scheduler',
	'EventBridge Schema Registry',
	'EventBridge Schema',
	'File Cache Hybrid NFS Linked Datasets',
	'File Cache On Premises NFS Linked Datasets',
	'File Cache S3 Linked Datasets',
	'FSX File Gateway',
	'FSX For NetApp ONTAP',
	'Glue Crawler',
	'Glue Data Catalog',
	'Glue Data Quality',
	'Glue',
	'Identity Access Management Add On',
	'Identity Access Management Data Encryption Key',
	'Identity Access Management Encrypted Data',
	'Identity Access Management IAM Access Analyzer',
	'Identity Access Management IAM Roles Anywhere',
	'Identity Access Management Long Term Security Credential',
	'Identity Access Management MFA Token',
	'Identity Access Management Permissions',
	'Identity Access Management Role',
	'Identity Access Management Temporary Security Credential',
	'Identity Access Management',
	'Inspector Agent',
	'IoT Action',
	'IoT Actuator',
	'IoT Alexa Enabled Device',
	'IoT Alexa Skill',
	'IoT Alexa Voice Service',
	'IoT Analytics Channel',
	'IoT Analytics Data Store',
	'IoT Analytics Dataset',
	'IoT Analytics Notebook',
	'IoT Analytics Pipeline',
	'IoT Certificate',
	'IoT Core Device Advisor',
	'IoT Core Device Location',
	'IoT Desired State',
	'IoT Device Defender IoT Device Jobs',
	'IoT Device Gateway',
	'IoT Device Management Fleet Hub',
	'IoT Device Tester',
	'IoT Echo',
	'IoT Fire TV Stick',
	'IoT Fire TV',
	'IoT Greengrass Artifact',
	'IoT Greengrass Component Machine Learning',
	'IoT Greengrass Component Nucleus',
	'IoT Greengrass Component Private',
	'IoT Greengrass Component Public',
	'IoT Greengrass Component',
	'IoT Greengrass Connector',
	'IoT Greengrass Interprocess Communication',
	'IoT Greengrass Protocol',
	'IoT Greengrass Recipe',
	'IoT Greengrass Stream Manager',
	'IoT Hardware Board',
	'IoT HTTP Protocol',
	'IoT HTTP2 Protocol',
	'IoT Lambda Function',
	'IoT Lorawan Protocol',
	'IoT MQTT Protocol',
	'IoT Over Air Update',
	'IoT Policy',
	'IoT Reported State',
	'IoT Rule',
	'IoT Sailboat',
	'IoT Sensor',
	'IoT Servo',
	'IoT Shadow',
	'IoT Simulator',
	'IoT Sitewise Asset Hierarchy',
	'IoT Sitewise Asset Model',
	'IoT Sitewise Asset Properties',
	'IoT Sitewise Asset',
	'IoT Sitewise Data Streams',
	'IoT Thing Bank',
	'IoT Thing Bicycle',
	'IoT Thing Camera',
	'IoT Thing Car',
	'IoT Thing Cart',
	'IoT Thing Coffee Pot',
	'IoT Thing Door Lock',
	'IoT Thing Factory',
	'IoT Thing Freertos Device',
	'IoT Thing Generic',
	'IoT Thing House',
	'IoT Thing Humidity Sensor',
	'IoT Thing Industrial PC',
	'IoT Thing Lightbulb',
	'IoT Thing Medical Emergency',
	'IoT Thing PLC',
	'IoT Thing Police Emergency',
	'IoT Thing Relay',
	'IoT Thing Stacklight',
	'IoT Thing Temperature Humidity Sensor',
	'IoT Thing Temperature Sensor',
	'IoT Thing Temperature Vibration Sensor',
	'IoT Thing Thermostat',
	'IoT Thing Travel',
	'IoT Thing Utility',
	'IoT Thing Vibration Sensor',
	'IoT Thing Windfarm',
	'IoT Topic',
	'Key Management Service External Key Store',
	'Lake Formation Data Lake',
	'Lambda Function',
	'License Manager Application Discovery',
	'License Manager License Blending',
	'Location Service Geofence',
	'Location Service Map ',
	'Location Service Place',
	'Location Service Routes',
	'Location Service Track ',
	'Mainframe Modernization Analyzer',
	'Mainframe Modernization Compiler',
	'Mainframe Modernization Converter',
	'Mainframe Modernization Developer',
	'Mainframe Modernization Runtime',
	'Managed Blockchain Blockchain',
	'Migration Hub Refactor Spaces Applications',
	'Migration Hub Refactor Spaces Environments',
	'Migration Hub Refactor Spaces Services',
	'MQ Broker',
	'MSK',
	'Network Firewall Endpoints',
	'OpenSearch Service Cluster Administrator Node',
	'OpenSearch Service Data Node',
	'OpenSearch Service Index',
	'OpenSearch Service Observability',
	'OpenSearch Dashboards',
	'OpenSearch Ingestion',
	'OpenSearch Service Traces',
	'OpenSearch Service Ultrawarm Node',
	'OpsWorks Apps',
	'OpsWorks Deployments',
	'OpsWorks Instances',
	'OpsWorks Layers',
	'OpsWorks Monitoring',
	'OpsWorks Permissions',
	'OpsWorks Resources',
	'OpsWorks Stack2',
	'Organizations Account',
	'Organizations Management Account',
	'Organizations Organizational Unit',
	'Pinpoint Journey',
	'Quicksight Paginated Reports',
	'RDS Blue Green Deployments',
	'RDS Multi AZ DB Cluster',
	'RDS Multi AZ',
	'RDS Optimized Writes',
	'RDS Proxy Instance Alternate',
	'RDS Proxy Instance',
	'RDS Trusted Language Extensions For PostgreSQL',
	'Redshift Auto Copy',
	'Redshift Data Sharing Governance',
	'Redshift Dense Compute Node',
	'Redshift Dense Storage Node',
	'Redshift ML',
	'Redshift Query Editor V2',
	'Redshift RA3',
	'Redshift Streaming Ingestion',
	'Rekognition Image',
	'Rekognition Video',
	'RoboMaker Cloud Extensions Ros',
	'RoboMaker Development Environment',
	'RoboMaker Fleet Management',
	'RoboMaker Simulation',
	'Route 53 Hosted Zone',
	'Route 53 Readiness Checks',
	'Route 53 Resolver Dns Firewall',
	'Route 53 Resolver Query Logging',
	'Route 53 Resolver',
	'Route 53 Route 53 Application Recovery Controller',
	'Route 53 Route Table',
	'Route 53 Routing Controls',
	'S3 File Gateway',
	'S3',
	'SageMaker Canvas',
	'SageMaker Geospatial ML',
	'SageMaker Model',
	'SageMaker Notebook',
	'SageMaker Shadow Testing',
	'SageMaker Train',
	'Security Hub Finding',
	'Shield',
	'Simple Email Service Email',
	'Simple Notification Service Email Notification',
	'Simple Notification Service HTTP Notification',
	'Simple Notification Service Topic',
	'Simple Queue Service Message',
	'Simple Queue Service Queue',
	'Simple Storage Service Bucket With Objects',
	'Simple Storage Service Directory Bucket',
	'Simple Storage Service General Access Points',
	'Simple Storage Service General Purpose Bucket',
	'Simple Storage Service Glacier Archive',
	'Simple Storage Service Glacier Vault',
	'Simple Storage Service Object',
	'Simple Storage Service S3 Batch Operations',
	'Simple Storage Service S3 Express One Zone',
	'Simple Storage Service S3 Glacier Deep Archive',
	'Simple Storage Service S3 Glacier Flexible Retrieval',
	'Simple Storage Service S3 Glacier Instant Retrieval',
	'Simple Storage Service S3 Intelligent Tiering',
	'Simple Storage Service S3 Multi Region Access Points',
	'Simple Storage Service S3 Object Lambda Access Points',
	'Simple Storage Service S3 Object Lambda',
	'Simple Storage Service S3 Object Lock',
	'Simple Storage Service S3 On Outposts',
	'Simple Storage Service S3 One Zone IA',
	'Simple Storage Service S3 Replication Time Control',
	'Simple Storage Service S3 Replication',
	'Simple Storage Service S3 Select',
	'Simple Storage Service S3 Standard IA',
	'Simple Storage Service S3 Standard',
	'Simple Storage Service S3 Storage Lens',
	'Simple Storage Service VPC Access Points',
	'Snowball Snowball Import Export',
	'Storage Gateway Cached Volume',
	'Storage Gateway File Gateway',
	'Storage Gateway Noncached Volume',
	'Storage Gateway Tape Gateway',
	'Storage Gateway Virtual Tape Library',
	'Storage Gateway Volume Gateway',
	'Systems Manager Application Manager',
	'Systems Manager Automation',
	'Systems Manager Change Calendar',
	'Systems Manager Change Manager',
	'Systems Manager Compliance',
	'Systems Manager Distributor',
	'Systems Manager Documents',
	'Systems Manager Incident Manager',
	'Systems Manager Inventory',
	'Systems Manager Maintenance Windows',
	'Systems Manager Opscenter',
	'Systems Manager Parameter Store',
	'Systems Manager Patch Manager',
	'Systems Manager Run Command',
	'Systems Manager Session Manager',
	'Systems Manager State Manager',
	'Textract Analyze Lending',
	'Transfer Family',
	'Transit Gateway Attachment',
	'Trusted Advisor Checklist Cost',
	'Trusted Advisor Checklist Fault Tolerant',
	'Trusted Advisor Checklist Performance',
	'Trusted Advisor Checklist Security',
	'Trusted Advisor Checklist',
	'VPC Carrier Gateway',
	'VPC Customer Gateway',
	'VPC Elastic Network Adapter',
	'VPC Elastic Network Interface',
	'VPC Endpoints',
	'VPC Flow Logs',
	'VPC Internet Gateway',
	'VPC NAT Gateway',
	'VPC Network Access Analyzer',
	'VPC Network Access Control List',
	'VPC Peering Connection',
	'VPC Reachability Analyzer',
	'VPC Router',
	'VPC Traffic Mirroring',
	'VPC Virtual Private Cloud VPC',
	'VPC VPN Connection',
	'VPC VPN Gateway',
	'WAF Bad Bot',
	'WAF Bot Control',
	'WAF Bot',
	'WAF Filtering Rule',
	'WAF Labels',
	'WAF Managed Rule',
	'WAF Rule',
	'Workspaces Family',
] as const;
